### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openrewrite/java/internal/template/AbstractRefasterJavaVisitor

### ISSUE THREAD

**Issue by nagkumar** [openrewrite/rewrite-java-security#109]
> Task :rewriteRun
Unable to configure org.openrewrite.java.migrate.apache.commons.io.ApacheCommonsFileUtilsRecipes
java.lang.NoClassDefFoundError: org/openrewrite/java/internal/template/AbstractRefasterJavaVisitor
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at org.openrewrite.gradle.RewriteClassLoader.loadClass(RewriteClassLoader.java:59)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at org.openrewrite.java.migrate.apache.commons.io.ApacheCommonsFileUtilsRecipes.getRecipeList(ApacheCommonsFileUtilsRecipes.java:37)
        at org.openrewrite.Recipe.createRecipeDescriptor(Recipe.java:152)
        at org.openrewrite.Recipe.getDescriptor(Recipe.java:144)
        at org.openrewrite.config.ClasspathScanningLoader.configureRecipes(ClasspathScanningLoader.java:176)
        at org.openrewrite.config.ClasspathScanningLoader.scanClasses(ClasspathScanningLoader.java:145)
        at org.openrewrite.config.ClasspathScanningLoader.<init>(ClasspathScanningLoader.java:74)
        at org.openrewrite.config.Environment$Builder.scanClassLoader(Environment.java:229)
        at org.openrewrite.gradle.isolated.DefaultProjectParser.environment(DefaultProjectParser.java:572)
        at org.openrewrite.gradle.isolated.DefaultProjectParser.listResults(DefaultProjectParser.java:1121)
        at org.openrewrite.gradle.isolated.DefaultProjectParser.run(DefaultProjectParser.java:398)
        at org.openrewrite.gradle.DelegatingProjectParser.lambda$run$2(DelegatingProjectParser.java:100)
        at org.openrewrite.gradle.DelegatingProjectParser.unwrapInvocationException(DelegatingProjectParser.java:147)
        at org.openrewrite.gradle.DelegatingProjectParser.run(DelegatingProjectParser.java:99)
        at org.openrewrite.gradle.RewriteRunTask.run(RewriteRunTask.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:248)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:233)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:216)
        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:199)

**Comment by timtebeek** [comment]
Hi @nagkumar ; It's not immediately clear what command you've run, or how that fails. There's little sense in running `:rewriteRun` against this repository, and a plain `./gradlew build` works just fine. I'll close this issue as something we can't reproduce, nor have enough detail about what you wanted to achieve. Feel free provide more detail if you this experience issues; In that case it's probably best to use [the bug report template](https://github.com/openrewrite/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) we provide, and which you should get as a prompt when you open a new issue.

**Comment by timtebeek** [comment]
Continued in https://github.com/openrewrite/rewrite-java-security/issues/110#issuecomment-1772423291
