### ISSUE TITLE
`SecureSnakeYamlConstructorTest` fails due to `AST contains missing or invalid type information` error

### ISSUE THREAD

**Issue by JLLeitschuh** [openrewrite/rewrite-java-security#83]
```
SecureSnakeYamlConstructorTest > doFixYamlIfSnakeYamlIsReturned() FAILED
    java.lang.IllegalStateException: AST contains missing or invalid type information
    NewClass->NewClass->Return->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
    /*~~(NewClass type is missing or malformed)~~>*/new SafeConstructor()
        at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:88)
        at org.openrewrite.java.Assertions.validateTypes(Assertions.java:63)
        at org.openrewrite.java.Assertions$$Lambda$404/0x0000000800d56000.accept(Unknown Source)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:428)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:123)
        at org.openrewrite.java.security.marshalling.SecureSnakeYamlConstructorTest.doFixYamlIfSnakeYamlIsReturned(SecureSnakeYamlConstructorTest.java:304)

SecureSnakeYamlConstructorTest > doFixYamlIfYamlPassedAsArgument() FAILED
    java.lang.IllegalStateException: AST contains missing or invalid type information
    NewClass->NewClass->NamedVariable->VariableDeclarations->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
    /*~~(NewClass type is missing or malformed)~~>*/new SafeConstructor()
        at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:88)
        at org.openrewrite.java.Assertions.validateTypes(Assertions.java:63)
        at org.openrewrite.java.Assertions$$Lambda$404/0x0000000800d56000.accept(Unknown Source)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:428)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:123)
        at org.openrewrite.java.security.marshalling.SecureSnakeYamlConstructorTest.doFixYamlIfYamlPassedAsArgument(SecureSnakeYamlConstructorTest.java:163)

SecureSnakeYamlConstructorTest > doFixYamlIfYamlAssignedToClassVariableViaThis() FAILED
    java.lang.IllegalStateException: AST contains missing or invalid type information
    NewClass->NewClass->Assignment->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
    /*~~(NewClass type is missing or malformed)~~>*/new SafeConstructor()
        at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:88)
        at org.openrewrite.java.Assertions.validateTypes(Assertions.java:63)
        at org.openrewrite.java.Assertions$$Lambda$404/0x0000000800d56000.accept(Unknown Source)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:428)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:123)
        at org.openrewrite.java.security.marshalling.SecureSnakeYamlConstructorTest.doFixYamlIfYamlAssignedToClassVariableViaThis(SecureSnakeYamlConstructorTest.java:274)

SecureSnakeYamlConstructorTest > snakeYamlWithRepresenterArgument() FAILED
    org.opentest4j.AssertionFailedError: [The recipe should have made the following change to "Test.java"] 
    expected: 
      "import org.yaml.snakeyaml.DumperOptions;
      import org.yaml.snakeyaml.Yaml;
      import org.yaml.snakeyaml.constructor.SafeConstructor;
      import org.yaml.snakeyaml.representer.Representer;
  
      class Test {
          Object o = new Yaml(new SafeConstructor(), new Representer(), new DumperOptions());
      }"
     but was: 
      "import org.yaml.snakeyaml.Yaml;
      import org.yaml.snakeyaml.representer.Representer;
  
      class Test {
          Object o = new Yaml(new Representer());
      }"
        at java.base@17.0.1/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base@17.0.1/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base@17.0.1/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base@17.0.1/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:489)
        at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
        at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:123)
        at app//org.openrewrite.java.security.marshalling.SecureSnakeYamlConstructorTest.snakeYamlWithRepresenterArgument(SecureSnakeYamlConstructorTest.java:87)

SecureSnakeYamlConstructorTest > doFixYamlIfLoadIsOnlyMethodCalled() FAILED
    java.lang.IllegalStateException: AST contains missing or invalid type information
    NewClass->NewClass->NamedVariable->VariableDeclarations->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
    /*~~(NewClass type is missing or malformed)~~>*/new SafeConstructor()
        at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:88)
        at org.openrewrite.java.Assertions.validateTypes(Assertions.java:63)
        at org.openrewrite.java.Assertions$$Lambda$404/0x0000000800d56000.accept(Unknown Source)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:428)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:123)
        at org.openrewrite.java.security.marshalling.SecureSnakeYamlConstructorTest.doFixYamlIfLoadIsOnlyMethodCalled(SecureSnakeYamlConstructorTest.java:133)

SecureSnakeYamlConstructorTest > snakeYamlWithDumperArgument() FAILED
    java.lang.IllegalStateException: AST contains missing or invalid type information
    NewClass->NewClass->NamedVariable->VariableDeclarations->Block->ClassDeclaration->CompilationUnit
    /*~~(NewClass type is missing or malformed)~~>*/new SafeConstructor()

    NewClass->NewClass->NamedVariable->VariableDeclarations->Block->ClassDeclaration->CompilationUnit
    /*~~(NewClass type is missing or malformed)~~>*/new Representer()
        at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:88)
        at org.openrewrite.java.Assertions.validateTypes(Assertions.java:63)
        at org.openrewrite.java.Assertions$$Lambda$404/0x0000000800d56000.accept(Unknown Source)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:428)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:123)
        at org.openrewrite.java.security.marshalling.SecureSnakeYamlConstructorTest.snakeYamlWithDumperArgument(SecureSnakeYamlConstructorTest.java:60)

SecureSnakeYamlConstructorTest > snakeYamlConstructor() FAILED
    java.lang.IllegalStateException: AST contains missing or invalid type information
    NewClass->NewClass->NamedVariable->VariableDeclarations->Block->ClassDeclaration->CompilationUnit
    /*~~(NewClass type is missing or malformed)~~>*/new SafeConstructor()
        at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:88)
        at org.openrewrite.java.Assertions.validateTypes(Assertions.java:63)
        at org.openrewrite.java.Assertions$$Lambda$404/0x0000000800d56000.accept(Unknown Source)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:428)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:123)
        at org.openrewrite.java.security.marshalling.SecureSnakeYamlConstructorTest.snakeYamlConstructor(SecureSnakeYamlConstructorTest.java:36)

SecureSnakeYamlConstructorTest > doFixYamlIfYamlAssignedToClassVariable() FAILED
    java.lang.IllegalStateException: AST contains missing or invalid type information
    NewClass->NewClass->Assignment->Block->MethodDeclaration->Block->ClassDeclaration->CompilationUnit
    /*~~(NewClass type is missing or malformed)~~>*/new SafeConstructor()
        at org.openrewrite.java.Assertions.assertValidTypes(Assertions.java:88)
        at org.openrewrite.java.Assertions.validateTypes(Assertions.java:63)
        at org.openrewrite.java.Assertions$$Lambda$404/0x0000000800d56000.accept(Unknown Source)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:428)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:123)
        at org.openrewrite.java.security.marshalling.SecureSnakeYamlConstructorTest.doFixYamlIfYamlAssignedToClassVariable(SecureSnakeYamlConstructorTest.java:201)

```

**Comment by timtebeek** [comment]
Looks like this has since been fixed; let me know if there's anything else left to do!
